enable_color: true
enable_depth: true
align_depth.enable: true
enable_rgbd: true
enable_sync: true
pointcloud.enable: true
enable_gyro: true
enable_accel: true
publish_tf: true
unite_imu_method: 2
tf_publish_rate: 1.0
rgb_camera.color_profile: 848x480x30
depth_module.depth_profile: 848x480x30
depth_module.infra_profile: 848x480x30